name: Vinkdriver
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter 
  flutter_localizations:
      sdk: flutter 

  # Firebase
  firebase_core: ^0.5.1
  firebase_auth: ^0.18.2
  cloud_firestore: ^0.14.2
  firebase_storage: ^4.0.0
  firebase_messaging: ^7.0.3
  firebase_database: ^4.0.0
  
  # Time functions and other utils
  simple_moment: ^1.0.6
  timeago: ^2.0.27
  emoji_picker: ^0.1.0
  path_provider: ^1.6.0
  image_picker: ^0.6.7+11
  image_cropper: ^1.3.1
  file_picker: ^2.0.12  
  image: ^2.1.14
  shared_preferences: ^0.5.10
  streaming_shared_preferences: ^1.0.1
  url_launcher: ^5.6.0
  getflutter: ^1.1.3  
  webview_flutter: "^0.3.22+1"
  fluttertoast: ^7.1.1
  device_apps: ^1.2.0
  path: ^1.7.0
  datetime_picker_formfield: ^1.0.0
  intl: ^0.16.1
  http: ^0.12.1
  uuid: ^2.0.4
  flutter_cache_manager: ^2.0.0
  flushbar: ^1.5.0
  social_share: ^2.0.5
  share: any

  # Location and Gmaps
  # Gmaps libs
  provider: ^3.0.0
  location: ^2.3.5
  google_maps_flutter: ^0.5.28+1
  geolocator: ^5.3.1
  flutter_polyline_points: ^0.2.1
  geocoder: ^0.2.1
  map_launcher: ^0.12.2

  # Icons
  cupertino_icons: ^0.1.3
  font_awesome_flutter: ^8.2.0

  # Routes
  auto_route: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  auto_route_generator: ^0.2.1+3

flutter:
  uses-material-design: true

  assets:
    - assets/images/